<div class="box noborder">
<?= $html->error_messages_for($message); ?>
<? $form->form_for($message, array("controller" => "messages",
"action" => "send", "id" => $controller->recipient_user->username), array(), function($f) use
($html, $controller) { ?>
	<?= $f->label("recipient_user_id", "To:", array("class" => "required")); ?>
	<?= $html->link_to(h($controller->message->recipient->username),
		array("controller" => "users", "action" => "show", "id" =>
		$controller->message->recipient->username)); ?>
	<br />

	<?= $f->label("subject", "Subject:", array("class" => "required")); ?>
	<?= $f->text_field("subject", array("size" => 51)); ?>
	<br />

	<?= $f->text_area("body", array("size" => "70x5")); ?>
	<br />

	<p>
	<?= $f->submit_tag("Send Message"); ?>
	</p>
<? }); ?>
</div>
