# Please do not 'fix' style issues without a compelling, metrics-driven
# argument that a style change will materially improve cod equality.
# https://github.com/lobsters/lobsters/pull/460

# Project setup:
require:
  - ./extras/prohibit_form_for_and_form_tag.rb
  - ./extras/prohibit_safe_navigation.rb
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Include:
    - '**/*.rb'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
  Exclude:
    - Gemfile
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
  UseCache: false

# Cop configuration:

# Bundler

# Gemspec

# Layout
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/ArrayAlignment:
  Enabled: false
Layout/CaseIndentation:
  EnforcedStyle: end
Layout/ElseAlignment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/HashAlignment:
  Enabled: false
Layout/LineLength:
  Max: 100
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  SpaceBeforeBlockParameters: false
Layout/SpaceInsideRangeLiteral:
  Enabled: false

# Lint
Lint/SuppressedException:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

# Metrics
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

# Naming
Naming/AccessorMethodName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
# disabled until class vaiables in extras become constants
Naming/MethodParameterName:
  Enabled: false
Naming/VariableName:
  Enabled: false

# Performance

# Rails
Rails/Blank:
  Enabled: false
Rails/FilePath:
  Enabled: false
Rails/HttpStatus:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/Present:
  UnlessBlank: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/HelperInstanceVariable:
  Enabled: false

# RSpec
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
RSpec/NotToNot:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/ExpectChange:
  Enabled: false
RSpec/HookArgument:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/UnspecifiedException:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
Capybara/FeatureMethods:
  Enabled: false

# Security

# Style
Style/AndOr:
  EnforcedStyle: conditionals
Style/BlockDelimiters:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
# It would be nice to have this on, but I'm not up for writing 66 of these in
# the process of addressing the initial 4,489 cop warnings.
Style/Documentation:
  Enabled: false
  Exclude: [db/migrate/**/*, spec/**/*, test/**/*]
Style/DoubleNegation:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/GuardClause:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/InverseMethods:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/MultilineMemoization:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/NegatedIf:
  EnforcedStyle: postfix
Style/NegatedWhile:
  Enabled: false
Style/Next:
  Enabled: false
Style/NonNilCheck:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: compact
Style/RedundantBegin:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/RegexpLiteral:
  AllowInnerSlashes: true
Style/SafeNavigation:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/WhileUntilDo:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/YodaCondition:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false

Gemspec/DeprecatedAttributeAssignment: # new in 1.30
  Enabled: false
Gemspec/RequireMFA: # new in 1.23
  Enabled: false
Layout/LineContinuationLeadingSpace: # new in 1.31
  Enabled: false
Layout/LineContinuationSpacing: # new in 1.31
  Enabled: false
Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: false
Layout/SpaceBeforeBrackets: # new in 1.7
  Enabled: false
Lint/AmbiguousAssignment: # new in 1.7
  Enabled: false
Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: false
Lint/AmbiguousRange: # new in 1.19
  Enabled: false
Lint/ConstantOverwrittenInRescue: # new in 1.31
  Enabled: false
Lint/DeprecatedConstants: # new in 1.8
  Enabled: false
Lint/DuplicateBranch: # new in 1.3
  Enabled: false
Lint/DuplicateRegexpCharacterClassElement: # new in 1.1
  Enabled: false
Lint/EmptyBlock: # new in 1.1
  Enabled: false
Lint/EmptyClass: # new in 1.3
  Enabled: false
Lint/EmptyInPattern: # new in 1.16
  Enabled: false
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: false
Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: false
Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: false
Lint/NonAtomicFileOperation: # new in 1.31
  Enabled: false
Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: false
Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: false
Lint/RedundantDirGlobSort: # new in 1.8
  Enabled: false
Lint/RefinementImportMethods: # new in 1.27
  Enabled: false
Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: false
Lint/SymbolConversion: # new in 1.9
  Enabled: false
Lint/ToEnumArguments: # new in 1.1
  Enabled: false
Lint/TripleQuotes: # new in 1.9
  Enabled: false
Lint/UnexpectedBlockArity: # new in 1.5
  Enabled: false
Lint/UnmodifiedReduceAccumulator: # new in 1.1
  Enabled: false
Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: false
Naming/BlockForwarding: # new in 1.24
  Enabled: false
Security/CompoundHash: # new in 1.28
  Enabled: false
Security/IoMethods: # new in 1.22
  Enabled: false
Style/ArgumentsForwarding: # new in 1.1
  Enabled: false
Style/CollectionCompact: # new in 1.2
  Enabled: false
Style/DocumentDynamicEvalDefinition: # new in 1.1
  Enabled: false
Style/EndlessMethod: # new in 1.8
  Enabled: false
Style/EnvHome: # new in 1.29
  Enabled: false
Style/FetchEnvVar: # new in 1.28
  Enabled: false
Style/FileRead: # new in 1.24
  Enabled: false
Style/FileWrite: # new in 1.24
  Enabled: false
Style/HashConversion: # new in 1.10
  Enabled: false
Style/HashExcept: # new in 1.7
  Enabled: false
Style/IfWithBooleanLiteralBranches: # new in 1.9
  Enabled: false
Style/InPatternThen: # new in 1.16
  Enabled: false
Style/MapCompactWithConditionalBlock: # new in 1.30
  Enabled: false
Style/MapToHash: # new in 1.24
  Enabled: false
Style/MultilineInPatternThen: # new in 1.16
  Enabled: false
Style/NegatedIfElseCondition: # new in 1.2
  Enabled: false
Style/NestedFileDirname: # new in 1.26
  Enabled: false
Style/NilLambda: # new in 1.3
  Enabled: false
Style/NumberedParameters: # new in 1.22
  Enabled: false
Style/NumberedParametersLimit: # new in 1.22
  Enabled: false
Style/ObjectThen: # new in 1.28
  Enabled: false
Style/OpenStructUse: # new in 1.23
  Enabled: false
Style/QuotedSymbols: # new in 1.16
  Enabled: false
Style/RedundantArgument: # new in 1.4
  Enabled: false
Style/RedundantInitialize: # new in 1.27
  Enabled: false
Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: false
Style/SelectByRegexp: # new in 1.22
  Enabled: false
Style/StringChars: # new in 1.12
  Enabled: false
Style/SwapValues: # new in 1.1
  Enabled: false
Rails/ActionControllerTestCase: # new in 2.14
  Enabled: false
Rails/ActiveRecordCallbacksOrder: # new in 2.7
  Enabled: false
Rails/AddColumnIndex: # new in 2.11
  Enabled: false
Rails/AfterCommitOverride: # new in 2.8
  Enabled: false
Rails/AttributeDefaultBlockValue: # new in 2.9
  Enabled: false
Rails/CompactBlank: # new in 2.13
  Enabled: false
Rails/DeprecatedActiveModelErrorsMethods: # new in 2.14
  Enabled: false
Rails/DotSeparatedKeys: # new in 2.15
  Enabled: false
Rails/DuplicateAssociation: # new in 2.14
  Enabled: false
Rails/DuplicateScope: # new in 2.14
  Enabled: false
Rails/DurationArithmetic: # new in 2.13
  Enabled: false
Rails/EagerEvaluationLogMessage: # new in 2.11
  Enabled: false
Rails/ExpandedDateRange: # new in 2.11
  Enabled: false
Rails/FindById: # new in 2.7
  Enabled: false
Rails/I18nLazyLookup: # new in 2.14
  Enabled: false
Rails/I18nLocaleAssignment: # new in 2.11
  Enabled: false
Rails/I18nLocaleTexts: # new in 2.14
  Enabled: false
Rails/Inquiry: # new in 2.7
  Enabled: false
Rails/MailerName: # new in 2.7
  Enabled: false
Rails/MatchRoute: # new in 2.7
  Enabled: false
Rails/MigrationClassName: # new in 2.14
  Enabled: false
Rails/NegateInclude: # new in 2.7
  Enabled: false
Rails/Pluck: # new in 2.7
  Enabled: false
Rails/PluckInWhere: # new in 2.7
  Enabled: false
Rails/RedundantPresenceValidationOnBelongsTo: # new in 2.13
  Enabled: false
Rails/RedundantTravelBack: # new in 2.12
  Enabled: false
Rails/RenderInline: # new in 2.7
  Enabled: false
Rails/RenderPlainText: # new in 2.7
  Enabled: false
Rails/RootJoinChain: # new in 2.13
  Enabled: false
Rails/RootPublicPath: # new in 2.15
  Enabled: false
Rails/ShortI18n: # new in 2.7
  Enabled: false
Rails/SquishedSQLHeredocs: # new in 2.8
  Enabled: false
Rails/StripHeredoc: # new in 2.15
  Enabled: false
Rails/TimeZoneAssignment: # new in 2.10
  Enabled: false
Rails/ToFormattedS: # new in 2.15
  Enabled: false
Rails/TransactionExitStatement: # new in 2.14
  Enabled: false
Rails/UnusedIgnoredColumns: # new in 2.11
  Enabled: false
Rails/WhereEquals: # new in 2.9
  Enabled: false
Rails/WhereExists: # new in 2.7
  Enabled: false
Rails/WhereNot: # new in 2.8
  Enabled: false
RSpec/BeEq: # new in 2.9.0
  Enabled: false
RSpec/BeNil: # new in 2.9.0
  Enabled: false
RSpec/ChangeByZero: # new in 2.11.0
  Enabled: false
RSpec/ExcessiveDocstringSpacing: # new in 2.5
  Enabled: false
RSpec/IdenticalEqualityAssertion: # new in 2.4
  Enabled: false
RSpec/SubjectDeclaration: # new in 2.5
  Enabled: false
RSpec/VerifiedDoubleReference: # new in 2.10.0
  Enabled: false
RSpec/Capybara/SpecificMatcher: # new in 2.12
  Enabled: false
RSpec/FactoryBot/SyntaxMethods: # new in 2.7
  Enabled: false
RSpec/Rails/AvoidSetupHook: # new in 2.4
  Enabled: false
RSpec/Rails/HaveHttpStatus: # new in 2.12
  Enabled: false
