# Project setup:
Rails:
  Enabled: true
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'

# Cop configuration:

# Bundler

# Gemspec

# Layout
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/CaseIndentation:
  EnforcedStyle: end
Layout/ElseAlignment:
  Enabled: false
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

# Lint
Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

# Metrics

# Naming

# Performance

# Rails
Rails/FilePath:
  Enabled: false

# Security

# Style
Style/IfUnlessModifier:
  Enabled: false
Style/NegatedIf:
  EnforcedStyle: postfix
Style/RedundantReturn:
  Enabled: false
Style/StringLiterals:
  Enabled: false
