# Use an official Ruby image as a base
FROM ruby:4.0.0

# Install dependencies
RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libjemalloc2 \
  libvips \
  mariadb-client \
  clang \
  vim

# Set working directory
WORKDIR /lobsters

# Set database hostname
ENV DATABASE_HOST db

# Install Bundler
RUN gem install bundler

# Copy Gemfile and Gemfile.lock
COPY Gemfile Gemfile.lock .ruby-version ./

# Copy bin/setup
COPY bin/setup ./bin/

# Copy database configuration
COPY config/database.yml.sample ./config/

# Setup the application
RUN bin/setup

# Expose port for Rails server
EXPOSE 3000

# Command to start the Rails server
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
