<div style="float: right;">
	<strong>
	<?= $html->link_to("Manage Your Items",
		array("controller" => "items", "action" => "manage")); ?>
	|
	<?= $html->link_to("List a New Item",
		array("controller" => "items", "action" => "build")); ?>
	</strong>
</div>

<h2><?= h($showing_user->username); ?></h2>
<div class="h2desc">
	a user for <?= $time->time_ago_in_words($showing_user->created_at); ?>
</div>

<p>
<div class="box noborder">
<? $form->form_for($showing_user, array("controller" => "users",
"action" => "update"), array("autocomplete" => "off"), function($f)
use ($html) { ?>
	<?= $html->error_messages_for($f->form_object); ?>

	<?= $f->label("username", "Username:", array("class" => "required")); ?>
	<span><?= h($f->form_object->username); ?></span>
	<br />

	<?= $f->label("new_password", "New Password:"); ?>
	<?= $f->password_field("new_password", array("size" => 20)); ?>
	<br />

	<?= $f->label("new_password_confirmation", "Password (Again):"); ?>
	<?= $f->password_field("new_password_confirmation", array("size" => 20)); ?>
	<br />

	<?= $f->label("email", "E-Mail Address:", array("class" => "required")); ?>
	<?= $f->text_field("email", array("size" => 20)); ?>
	<br />

	<label class="required">Settings:</label>

	<?= $f->check_box("email_notifications"); ?>
	<?= $f->label("email_notifications", "Receive E-Mail Notifications For "
		. "New Messages", array("class" => "norm")); ?>
	<br />

	<p>
	<?= $f->submit_tag("Save Settings"); ?>
	</p>
<? }); ?>
</div>
</p>
