<h2><?= h($showing_user->username); ?></h2>
<div class="h2desc">
	a user for <?= $time->time_ago_in_words($showing_user->created_at); ?>
</div>

<p>
<? if (count($items->collection)) { ?>
	<?= $controller->render(array("partial" => "items/list"),
		array("items" => $items)); ?>
<? } else { ?>
	<strong>No Items Listed</strong>
<? } ?>
</p>

<p>
<strong>Contact</strong><br />
<ul>
<li><?= $html->link_to("Send Message",
	array("controller" => "messages", "action" => "compose", "id" =>
	$showing_user->username)); ?>
<li><?= $html->link_to("View Hacker News Profile",
	"http://news.ycombinator.com/user?id=" . h($showing_user->username)); ?>
</ul>
</p>
