default: &default
  database: cache
  store_options:
    # Cap age of oldest cache entry to fulfill retention policies
    max_age: <%= 2.weeks.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default

production:
  <<: *default
