---
trilogy: &trilogy
  adapter: trilogy
  encoding: utf8mb4
  host: <%= ENV['DATABASE_HOST'] || "127.0.0.1" %>
  port: 3306

postgres: &postgres
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  pool: 5

sqlite3: &sqlite3
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  primary:
    <<: *postgres
    database: lobsters_dev
    username: postgres
    password: localdev
  cache:
    <<: *sqlite3
    database: tmp/cache/cache.sqlite3
    migrations_paths: db/cache_migrate
  # # queue:
  #   <<: *sqlite3
  #   database: tmp/queue/queue.sqlite3
  #   migrations_paths: db/queue_migrate

test:
  <<: *postgres
  database: lobsters_test
  username: postgres
  password: localdev

production:
  primary:
    <<: *trilogy
  cache:
    <<: *sqlite3
    database: /srv/lobste.rs/cache/cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *sqlite3
    database: /srv/lobste.rs/queue/queue.sqlite3
    migrations_paths: db/queue_migrate
