#!/bin/sh

if [ -f /srv/lobste.rs/http/public/maintenance.html ];
then
  exit 0
fi

find /srv/lobste.rs/http/public/cache/ -type f -not -mmin 2 -not -name ".gitkeep" -delete
find /srv/lobste.rs/http/public/cache/ -type d -empty -delete
