#!/usr/bin/env ruby

# Maintenance for the traffic intensity on the logo, see TrafficHelper

ENV["RAILS_ENV"] ||= "production"

APP_PATH = File.expand_path('../../config/application', __FILE__)
require File.expand_path('../../config/boot', __FILE__)
require APP_PATH
Rails.application.require_environment!

# calculate and cache activity range for traffic
TrafficHelper.cache_traffic!
