export EDITOR=vim
export HISTFILESIZE=$HISTSIZE
export HISTIGNORE=[fb]g
export HISTSIZE=100000
export PAGER="less -R"

alias be="bundle exec"
alias c="curl"
alias cl="clear"
alias con="cd ~deploy/lobsters/current; bundle exec rails console"
alias db="cd ~deploy/lobsters/current; bundle exec rails db -p"
alias e="exa"
alias et="exa -snew"
alias fd="fdfind"
alias gerp="grep"
alias g="git"
alias log="cd ~deploy/lobsters/shared/log"
alias vi="vim"

set -o vi
