# footgun: lot of shared settings between these two, but it can't be extracted
# to a shared *.log stanza because logrotate will abort with "duplicate log
# entry" if two stanzas apply to a logfile. We could share settings in the global
# scope but then that hits every other logfile in every other dir.

/home/deploy/*/shared/log/caddy.log {
  # ~5GiB/day so rotate daily
  daily 
  rotate 112

  compress
  compresscmd /bin/bzip2
  compressext .bz2
  compressoptions -9
  copytruncate
  create
  dateext
  delaycompress
  maxsize 10G
  missingok
  norenamecopy
  notifempty
  shred
  shredcycles 1
  su deploy deploy
}

/home/deploy/*/shared/log/action.log
/home/deploy/*/shared/log/rails.log
/home/deploy/*/shared/log/solid_queue.log {
  # much much less so rotate weekly
  rotate 16
  weekly

  compress
  compresscmd /bin/bzip2
  compressext .bz2
  compressoptions -9
  copytruncate
  create
  dateext
  delaycompress
  maxsize 10G
  missingok
  norenamecopy
  notifempty
  shred
  shredcycles 1
  su deploy deploy
}
