#!/bin/bash

if [ -z "${SITESLUG:-}" ]; then
    echo "Error: SITESLUG environment variable is not set, must match the app name setting"
    exit 1
fi
if [ ! -d "/home/deploy/$SITESLUG" ]; then
    echo "/home/deploy/$SITESLUG does not exist, SITESLUG env var must not match app name setting"
    exit 1
fi

cp /home/deploy/$SITESLUG/shared/etc/credentials.yml.enc config/credentials.yml.enc
cp /home/deploy/$SITESLUG/shared/etc/master.key config/master.key
cp /home/deploy/$SITESLUG/shared/etc/database.yml config/database.yml
