#!/usr/bin/bash

set -e
cd /home/deploy/lobsters/current/hatchbox

# This is a series of workarounds for misdesigns:
#
# 1. Hatchbox can't run scripts as root on deploy. This script provisions and
#    configures system services and such an important script must live in the
#    repo.
#
# 2. A service unit can't use PathChanged itself, it requires a path unit.
#    That's root-deploy.path.
#
# 3. A path unit can't use ExecStart itself, it requires a service unit.
#    That's root-deploy.service.
#
# 4. Path units have an unfixed bug: https://github.com/systemd/systemd/issues/17727
#    Systemd fails to consider a replaced symlink as 'changed' or 'modified'.
#    So .hatchbox/post-deploy touches the symlink on boot.
#
# 5. https://i.imgur.com/MCHXwyi.jpeg

APP_ETC=/home/deploy/lobsters/shared/etc

# the only way to get a PTR on DO name the VPS with the fqdn, ugh
# https://docs.digitalocean.com/products/networking/dns/how-to/manage-records/#ptr-rdns-records
echo "lobste.rs" > /etc/hostname

# Install Anubis
if [ ! -f /tmp/anubis_1.27.0_amd64.deb ]; then
  curl -Ls https://github.com/TecharoHQ/anubis/releases/download/v1.27.0/anubis_1.27.0_amd64.deb \
         -o /tmp/anubis_1.27.0_amd64.deb
  apt install /tmp/anubis_1.27.0_amd64.deb
fi

# server packages
apt install iptables-persistent opendkim postfix restic

# We build our own sqlite3 (.bundle/config), remove any system copy to avoid
# infinite confusion when getting different query plans from a different version.
apt remove -y sqlite3

# 2026-01-02 workaround failure to build commonmarker because there aren't
# precompiled gems for ruby 4.0.0 yet
# https://github.com/gjtorikian/commonmarker/issues/427
apt install libclang-dev

# configure opendkim for postfix
cp -a opendkim.m4 /etc/mail/m4/
cp -a opendkim.conf /etc/
cp -a opendkim.service /etc/systemd/system/
if [ ! -f /etc/dkimkeys/mail.private ]; then
  opendkim-genkey --verbose --restrict --selector=mail --subdomains --domain=lobste.rs --directory=/etc/dkimkeys/
fi
mkdir -p /var/spool/postfix/opendkim
chown -R opendkim:opendkim /var/spool/postfix/opendkim /etc/dkimkeys
systemctl restart opendkim

# configure postfix
adduser postfix opendkim
cp -a main.cf master.cf virtual_aliases transport /etc/postfix/
postmap /etc/postfix/virtual_aliases
postmap /etc/postfix/transport
postfix reload

# I get bounces daily from journalduhacker.net who left my email in their config.
cp -a aliases /etc/
ADMIN_EMAIL=$(cat $APP_ETC/admin_email)
sed -i "s/ADMIN_EMAIL/$ADMIN_EMAIL/g" /etc/aliases
newaliases

# https://github.com/lobsters/lobsters/issues/1739
cp -a syslog.conf  /usr/lib/systemd/journald.conf.d/
systemctl force-reload systemd-journald

# keep Caddy's per-request access logs out of journald (they're in caddy.log).
cp -a caddy-no-access-journal.conf /etc/systemd/system/caddy.service.d/

# Configure Anubis
cp -a lobsters.anubis.env /etc/anubis/lobsters.env
cp -a lobsters.botPolicies.yaml /etc/anubis/lobsters.botPolicies.yaml

# pick up changes to services, of course there is no "restart iff changed" command
changed_services=$(systemctl list-units --type=service --state=active --no-legend | awk '{print $1}' | xargs systemctl show -p NeedDaemonReload | grep 'NeedDaemonReload=yes' -B 1 | grep 'Id=' | cut -d= -f)

systemctl daemon-reload
systemctl enable --now anubis@lobsters.service
systemctl enable --now opendkim
systemctl enable --now postfix

for service in ${changed_services}; do
  systemctl restart "$service"
done


# quiet logins
cp -a sshd_config /etc/ssh/sshd_config

# configure logrotate
cp -a logrotate.conf /etc/logrotate.d/
# rm hatchbox's config; logrotate precendence is unreliable
rm -f /etc/logrotate.d/hatchbox_logrotate.conf

# shell quality of life
apt install eza fd-find ncdu tmux tree

# shell config; the default .bashrc sources this
cp -a bash_aliases /root/.bash_aliases
cp -a bash_aliases ~deploy/.bash_aliases
chown deploy:deploy ~deploy/.bash_aliases

cp -a sqliterc /root/.sqliterc
cp -a sqliterc ~deploy/.sqliterc
chown deploy:deploy ~deploy/.sqliterc

# make iptables record readable for transparency
netfilter-persistent save
chmod go+r /etc/iptables/rules.v4 /etc/iptables/rules.v6

# run restic to back up /etc
export HOME=/root
source $APP_ETC/restic-env
restic backup --cleanup-cache --no-scan /etc
