name: "Build and Push Docker Containers for Scrapers to Registry"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TAG_PREFIX: ""

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker setup
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/aqora-io/quantumnews-scrapers
          file: scrapers/Dockerfile
          flavor: |
            latest=false
          tags: |
            type=schedule
            type=ref,event=branch,prefix=${{ env.TAG_PREFIX }}branch-
            type=ref,event=tag,prefix=${{ env.TAG_PREFIX }}tag-
            type=ref,event=pr,prefix=${{ env.TAG_PREFIX }}pr-
            # set latest tag for default branch
            type=raw,value=latest,prefix=${{ env.TAG_PREFIX }},enable={{is_default_branch}}
            type=semver,pattern={{version}},value=v${{ steps.cargo_version.outputs.value }},prefix=${{ env.TAG_PREFIX }},enable={{is_default_branch}}

      - name: Docker
        uses: docker/build-push-action@v5
        with:
          file: scrapers/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
